package com.example.data.repository

import android.content.Context
import com.example.data.local.AppDatabase
import com.example.data.local.SecureStorage
import com.example.data.local.entities.AppSettingEntity
import com.example.data.local.entities.ConversationEntity
import com.example.data.local.entities.MessageEntity
import com.example.data.local.entities.ProviderConfigEntity
import com.example.model.AiModelInfo
import com.example.model.AiProviderType
import com.example.model.ChatMessage
import com.example.model.ComparisonTileState
import com.example.model.MessageRole
import com.example.model.ModelCatalog
import com.example.network.ChatMessagePayload
import com.example.network.KeyValidationResult
import com.example.network.ProviderRegistry
import com.example.network.ProviderResponse
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import java.util.UUID

class ChatRepository(context: Context) {
    private val database = AppDatabase.getDatabase(context)
    private val conversationDao = database.conversationDao()
    private val messageDao = database.messageDao()
    private val providerConfigDao = database.providerConfigDao()
    private val appSettingDao = database.appSettingDao()

    val allConversations: Flow<List<ConversationEntity>> = conversationDao.getAllConversations()
    val allFolders: Flow<List<String>> = conversationDao.getAllFolders()
    val allProviderConfigs: Flow<List<ProviderConfigEntity>> = providerConfigDao.getAllConfigs()

    fun getMessagesForConversation(conversationId: String): Flow<List<ChatMessage>> {
        return messageDao.getMessagesForConversation(conversationId).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    suspend fun createNewConversation(
        title: String = "New Session",
        provider: AiProviderType = AiProviderType.GEMINI,
        modelId: String = "gemini-3.5-flash",
        folderName: String? = null
    ): ConversationEntity = withContext(Dispatchers.IO) {
        val id = UUID.randomUUID().toString()
        val conv = ConversationEntity(
            id = id,
            title = title,
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis(),
            folderName = folderName,
            lastProvider = provider.id,
            lastModelId = modelId
        )
        conversationDao.insert(conv)
        conv
    }

    suspend fun updateConversationTitle(id: String, title: String) = withContext(Dispatchers.IO) {
        conversationDao.updateTitle(id, title)
    }

    suspend fun togglePin(id: String) = withContext(Dispatchers.IO) {
        conversationDao.togglePin(id)
    }

    suspend fun toggleFavorite(id: String) = withContext(Dispatchers.IO) {
        conversationDao.toggleFavorite(id)
    }

    suspend fun setFolder(id: String, folder: String?) = withContext(Dispatchers.IO) {
        conversationDao.setFolder(id, folder)
    }

    suspend fun deleteConversation(id: String) = withContext(Dispatchers.IO) {
        messageDao.deleteForConversation(id)
        conversationDao.deleteById(id)
    }

    suspend fun deleteMessage(id: String) = withContext(Dispatchers.IO) {
        messageDao.deleteById(id)
    }

    suspend fun updateMessage(id: String, content: String) = withContext(Dispatchers.IO) {
        messageDao.updateContent(id, content)
    }

    suspend fun clearAllHistory() = withContext(Dispatchers.IO) {
        messageDao.deleteAll()
        conversationDao.deleteAll()
    }

    suspend fun exportConversationAsMarkdown(conversationId: String): String = withContext(Dispatchers.IO) {
        val conv = conversationDao.getConversationById(conversationId) ?: return@withContext ""
        val messages = messageDao.getMessagesList(conversationId)
        val sb = StringBuilder()
        sb.append("# ${conv.title}\n\n")
        sb.append("*Generated by Nexus AI Workstation on ${java.util.Date(conv.updatedAt)}*\n\n---\n\n")

        for (msg in messages) {
            val roleLabel = if (msg.role == "user") "### User" else "### Assistant (${msg.provider} - ${msg.modelId})"
            sb.append("$roleLabel\n\n")
            if (!msg.thinkingContent.isNullOrBlank()) {
                sb.append("> **Thinking Process:**\n> ${msg.thinkingContent.replace("\n", "\n> ")}\n\n")
            }
            sb.append("${msg.content}\n\n---\n\n")
        }
        sb.toString()
    }

    suspend fun sendMessage(
        conversationId: String,
        userPrompt: String,
        providerType: AiProviderType,
        modelId: String,
        temperature: Float = 0.7f,
        thinkingLevel: String? = null,
        enableWebSearch: Boolean = false,
        imageBase64: String? = null,
        onStreamingChunk: suspend (accumulatedText: String, isThinking: Boolean) -> Unit
    ): ProviderResponse = withContext(Dispatchers.IO) {
        // 1. Insert user message
        val userMsgId = UUID.randomUUID().toString()
        val userEntity = MessageEntity(
            id = userMsgId,
            conversationId = conversationId,
            role = "user",
            content = userPrompt,
            timestamp = System.currentTimeMillis(),
            provider = providerType.id,
            modelId = modelId,
            imageBase64 = imageBase64
        )
        messageDao.insert(userEntity)

        // Auto-generate title if this is the first turn
        val existingMessages = messageDao.getMessagesList(conversationId)
        if (existingMessages.size <= 1) {
            val shortTitle = userPrompt.lines().firstOrNull()?.take(32) ?: "Chat Session"
            conversationDao.updateTitle(conversationId, shortTitle)
        }

        // 2. Fetch API key from config
        val config = providerConfigDao.getConfig(providerType.id)
        val decryptedKey = SecureStorage.decryptKey(config?.apiKeyEncrypted ?: "")
        val customEndpoint = config?.customEndpoint

        // 3. Build message history payload
        val payloads = existingMessages.map {
            ChatMessagePayload(
                role = it.role,
                content = it.content,
                imageBase64 = it.imageBase64
            )
        }

        // 4. Create temporary assistant entity
        val assistantMsgId = UUID.randomUUID().toString()
        val assistantEntity = MessageEntity(
            id = assistantMsgId,
            conversationId = conversationId,
            role = "assistant",
            content = "",
            timestamp = System.currentTimeMillis(),
            provider = providerType.id,
            modelId = modelId
        )
        messageDao.insert(assistantEntity)

        // 5. Stream response
        val adapter = ProviderRegistry.getAdapter(providerType)
        val accumulated = StringBuilder()

        val response = adapter.streamResponse(
            apiKey = decryptedKey,
            modelId = modelId,
            messages = payloads,
            endpoint = customEndpoint,
            temperature = temperature,
            thinkingLevel = thinkingLevel,
            enableWebSearch = enableWebSearch,
            onChunkReceived = { chunk ->
                accumulated.append(chunk)
                messageDao.updateContent(assistantMsgId, accumulated.toString())
                onStreamingChunk(accumulated.toString(), false)
            }
        )

        // 6. Finalize assistant entity
        val finalEntity = assistantEntity.copy(
            content = if (response.error != null) "⚠️ ${response.error}" else response.text,
            tokensCount = response.tokensCount,
            latencyMs = response.latencyMs,
            thinkingContent = response.thinkingContent,
            isError = response.error != null
        )
        messageDao.insert(finalEntity)

        response
    }

    suspend fun executeComparePrompt(
        prompt: String,
        selectedModels: List<Pair<AiProviderType, String>>,
        temperature: Float = 0.7f,
        onUpdateTile: (ComparisonTileState) -> Unit
    ) = coroutineScope {
        selectedModels.map { (provider, modelId) ->
            async(Dispatchers.IO) {
                val start = System.currentTimeMillis()
                onUpdateTile(
                    ComparisonTileState(
                        modelId = modelId,
                        provider = provider,
                        responseText = "",
                        isGenerating = true
                    )
                )

                val config = providerConfigDao.getConfig(provider.id)
                val decryptedKey = SecureStorage.decryptKey(config?.apiKeyEncrypted ?: "")
                val endpoint = config?.customEndpoint
                val adapter = ProviderRegistry.getAdapter(provider)

                val accumulated = StringBuilder()
                val response = adapter.streamResponse(
                    apiKey = decryptedKey,
                    modelId = modelId,
                    messages = listOf(ChatMessagePayload(role = "user", content = prompt)),
                    endpoint = endpoint,
                    temperature = temperature,
                    onChunkReceived = { chunk ->
                        accumulated.append(chunk)
                        onUpdateTile(
                            ComparisonTileState(
                                modelId = modelId,
                                provider = provider,
                                responseText = accumulated.toString(),
                                isGenerating = true,
                                latencyMs = System.currentTimeMillis() - start
                            )
                        )
                    }
                )

                onUpdateTile(
                    ComparisonTileState(
                        modelId = modelId,
                        provider = provider,
                        responseText = if (response.error != null) "Error: ${response.error}" else response.text,
                        thinkingText = response.thinkingContent ?: "",
                        isGenerating = false,
                        latencyMs = response.latencyMs,
                        error = response.error
                    )
                )
            }
        }.awaitAll()
    }

    // API Key Manager operations
    suspend fun saveApiKey(
        providerType: AiProviderType,
        plainKey: String,
        endpoint: String? = null,
        defaultModelId: String? = null
    ) = withContext(Dispatchers.IO) {
        val encrypted = SecureStorage.encryptKey(plainKey)
        val existing = providerConfigDao.getConfig(providerType.id)
        val updated = (existing ?: ProviderConfigEntity(providerId = providerType.id)).copy(
            apiKeyEncrypted = encrypted,
            customEndpoint = endpoint,
            defaultModelId = defaultModelId ?: ModelCatalog.getDefaultModelForProvider(providerType).id,
            updatedAt = System.currentTimeMillis()
        )
        providerConfigDao.insertOrUpdate(updated)
    }

    suspend fun setProviderEnabled(providerType: AiProviderType, isEnabled: Boolean) = withContext(Dispatchers.IO) {
        providerConfigDao.setEnabled(providerType.id, isEnabled)
    }

    suspend fun deleteApiKey(providerType: AiProviderType) = withContext(Dispatchers.IO) {
        val existing = providerConfigDao.getConfig(providerType.id)
        if (existing != null) {
            providerConfigDao.insertOrUpdate(existing.copy(apiKeyEncrypted = "", lastTestedStatus = "UNTESTED"))
        }
    }

    suspend fun testProviderConnection(providerType: AiProviderType): KeyValidationResult = withContext(Dispatchers.IO) {
        val config = providerConfigDao.getConfig(providerType.id)
        val decryptedKey = SecureStorage.decryptKey(config?.apiKeyEncrypted ?: "")
        val endpoint = config?.customEndpoint
        val adapter = ProviderRegistry.getAdapter(providerType)
        val result = adapter.validateApiKey(decryptedKey, endpoint)
        providerConfigDao.updateTestStatus(
            providerId = providerType.id,
            status = if (result.isValid) "CONNECTED" else "ERROR",
            latencyMs = result.latencyMs
        )
        result
    }

    // App Settings
    suspend fun getSetting(key: String, defaultValue: String): String = withContext(Dispatchers.IO) {
        appSettingDao.getSetting(key) ?: defaultValue
    }

    suspend fun saveSetting(key: String, value: String) = withContext(Dispatchers.IO) {
        appSettingDao.setSetting(AppSettingEntity(key, value))
    }

    private fun MessageEntity.toDomainModel(): ChatMessage {
        return ChatMessage(
            id = id,
            conversationId = conversationId,
            role = when (role.lowercase()) {
                "user" -> MessageRole.USER
                "assistant", "model" -> MessageRole.ASSISTANT
                else -> MessageRole.SYSTEM
            },
            content = content,
            timestamp = timestamp,
            provider = AiProviderType.fromId(provider),
            modelId = modelId,
            tokensCount = tokensCount,
            latencyMs = latencyMs,
            thinkingContent = thinkingContent,
            isError = isError,
            imageBase64 = imageBase64
        )
    }
}
